service: whatsapp-webhooks
frameworkVersion: '3.35.2'

provider:
 name: aws
 runtime: nodejs18.x
 lambdaHashingVersion: 20201221
 environment:
   TOKEN: testtoken

plugins:
 - serverless-offline

functions:
 app:
   handler: handler.handler
   events:
     - http: ANY /
     - http:  ANY /{proxy+}